# Generated by Django 2.2.9 on 2020-02-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardCollections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPowerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('power_level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectionPriceBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardcollection',
            name='avg_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='cardCollections.CollectionPowerLevel'),
        ),
        migrations.AddField(
            model_name='cardcollection',
            name='price_bracket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='collections', to='cardCollections.CollectionPriceBracket'),
        ),
    ]
