# Generated by Django 2.2.9 on 2020-02-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('full_name', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=1000)),
                ('slug', models.CharField(max_length=1000)),
                ('alter_egos', models.CharField(max_length=1000)),
                ('aliases', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=1000)),
                ('publisher', models.CharField(max_length=1000)),
                ('alignment', models.CharField(max_length=1000)),
                ('occupation', models.CharField(max_length=1000)),
                ('affiliations', models.CharField(max_length=1000)),
            ],
        ),
    ]
