# Generated by Django 2.2.9 on 2020-02-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='affiliations',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='aliases',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='alignment',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='alter_egos',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='gender',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='occupation',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hero',
            name='publisher',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
