# Generated by Django 2.2.9 on 2020-02-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        ('cardCollections', '0002_auto_20200227_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcollection',
            name='cards',
            field=models.ManyToManyField(blank=True, related_name='collections', to='cards.PlayingCard'),
        ),
    ]
