# Generated by Django 2.2.9 on 2020-02-27 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heroes', '0002_auto_20200226_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPowerLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('power_level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardPriceBracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('intelligence', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('durability', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=0)),
                ('combat', models.IntegerField(default=0)),
                ('overall', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='heroes.Hero')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to='cards.CardPowerLevel')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to=settings.AUTH_USER_MODEL)),
                ('price_bracket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cards', to='cards.CardPriceBracket')),
            ],
        ),
    ]
